[versions]
circleimageview = "3.1.0"
dagger = "2.52"
gson = "2.11.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.6.1"
roomRuntime = "2.6.1"
rxjava = "2.2.21"

[libraries]
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-room-rxjava2 = { module = "androidx.room:room-rxjava2", version.ref = "roomRuntime" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
rxjava = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava" }
